#this file is designed to go with the shop file and will create the files needed in the correct places. This will also re-set the items and money bought.
f = open("money_s.txt","w")
f.write("60")
f.close()
f = open("money_m.txt","w")
f.write("40")
f.close()
f = open("money_l.txt","w")
f.write("20")
f.close()
f = open("money_x.txt","w")
f.write("10")
f.close()
f = open("amount.txt","w")
f.write("0")
f.close()
f = open("items.txt","w")
f.close()
print("done")
